### ISSUE TITLE
[FEATURE] Add more info to unreachable alert.

### ISSUE THREAD

**Issue by nickeskov** [wavesplatform/nodemon#97]
**Аbstract**
For now If any necessary request to node fails we see simple `UnreachableAlert` without any information about cause of such state.
It's good to have such information in alert message.
https://github.com/wavesplatform/nodemon/blob/18398d28db3338075c03e673a8774a4927909faa/pkg/scraping/scraper.go#L93-L118

**Comment by esuwu** [comment]
Has been fixed in one of the PRs
